#!/bin/bash --login
#PBS -N baseline
#PBS -l select=1
#PBS -A d154
#PBS -l place=excl
#PBS -l walltime=20:00:00

cd $PBS_O_WORKDIR

module load mpt
module load intel-compilers-17
source activate mlp
layertype='Relu Sigmoid LeakyRelu ELU SELU';
for layer in ${layertype}; do
    for i in `seq 1 3`; do
        python emnist_task_baseline.py --layer_type ${layer} --layer_num $i &
    done
done
wait
source deactivate


